server:
  port: 8112
spring:
  web:
    resources:
      #启动默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        #资源链启动缓存，默认启动
        #启用资源链，默认禁用
        #启用压缩资源(gzip,brotli)解析，默认禁用
        cache: true
        enabled: true
        compressed: true
      static-locations: classpath:/static/

  # thymelaef配置
  thymeleaf:
    # 关闭缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bishanpatent?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456

    hikari:
      #连接池名
      pool-name: DateHikariCP
      # 最小空闲连接出
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000(10分钟)
      idle-timeout: 600000
      #最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30000(30秒)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # 若没有找到拦截器抛出异常
  mvc:
    throw-exception-if-no-handler-found: true

#Mybatis配置
mybatis:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.cf.bishanpatent
  # 开启驼峰命名转换
  configuration:
    map-underscore-to-camel-case: false

# MyBatis SQL打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.lqh.beibeipatent.dao: debug